-- Cross-module references are scalar IDs. Foreign keys still protect this monolith's database.
-- Splitting a service requires a separate data-ownership and migration design.
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE access_tokens (
    token_hash VARCHAR(64) PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_tokens_expiry ON access_tokens(expires_at);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL REFERENCES members(id),
    title VARCHAR(120) NOT NULL,
    description VARCHAR(3000) NOT NULL,
    category VARCHAR(30) NOT NULL CHECK (category IN ('TCG','PHOTOCARD','LEGO','FIGURE','MODEL_KIT','SPORTS','OTHER')),
    item_condition VARCHAR(20) NOT NULL CHECK (item_condition IN ('SEALED','LIKE_NEW','GOOD','FAIR')),
    image_url VARCHAR(1000),
    status VARCHAR(20) NOT NULL CHECK (status IN ('AVAILABLE','LISTED','SOLD','DELETED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_products_seller ON products(seller_id, id DESC);
CREATE INDEX idx_products_category ON products(category, id DESC);

CREATE TABLE auctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('FORWARD','REVERSE')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN','CLOSED','CANCELLED')),
    owner_id BIGINT NOT NULL REFERENCES members(id),
    product_id BIGINT REFERENCES products(id),
    title VARCHAR(120) NOT NULL,
    description VARCHAR(3000) NOT NULL,
    category VARCHAR(30) NOT NULL CHECK (category IN ('TCG','PHOTOCARD','LEGO','FIGURE','MODEL_KIT','SPORTS','OTHER')),
    starting_price BIGINT NOT NULL CHECK (starting_price BETWEEN 1 AND 1000000000000),
    min_increment BIGINT NOT NULL CHECK (min_increment BETWEEN 0 AND 1000000000000),
    current_price BIGINT CHECK (current_price BETWEEN 1 AND 1000000000000),
    leading_bidder_id BIGINT REFERENCES members(id),
    winning_offer_id BIGINT,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CHECK (ends_at > created_at),
    CHECK ((current_price IS NULL) = (leading_bidder_id IS NULL)),
    CHECK (leading_bidder_id IS NULL OR leading_bidder_id <> owner_id),
    CHECK (kind <> 'FORWARD' OR (product_id IS NOT NULL AND min_increment >= 1)),
    CHECK (status <> 'CLOSED' OR closed_at IS NOT NULL)
);
CREATE INDEX idx_auctions_due ON auctions(ends_at, id) WHERE status = 'OPEN';
CREATE INDEX idx_auctions_search ON auctions(kind, category, id DESC);
CREATE INDEX idx_auctions_owner ON auctions(owner_id, id DESC);
CREATE UNIQUE INDEX uq_active_product ON auctions(product_id) WHERE status = 'OPEN' AND kind = 'FORWARD';

CREATE TABLE bids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id BIGINT NOT NULL REFERENCES auctions(id),
    bidder_id BIGINT NOT NULL REFERENCES members(id),
    amount BIGINT NOT NULL CHECK (amount BETWEEN 1 AND 1000000000000),
    request_key VARCHAR(36) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_bid_request UNIQUE (auction_id, bidder_id, request_key)
);
CREATE INDEX idx_bids_history ON bids(auction_id, id DESC);

CREATE TABLE offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id BIGINT NOT NULL REFERENCES auctions(id),
    seller_id BIGINT NOT NULL REFERENCES members(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    amount BIGINT NOT NULL CHECK (amount BETWEEN 1 AND 1000000000000),
    note VARCHAR(1000) NOT NULL,
    request_key VARCHAR(36) NOT NULL,
    product_title VARCHAR(120) NOT NULL,
    product_description VARCHAR(3000) NOT NULL,
    category VARCHAR(30) NOT NULL,
    product_condition VARCHAR(20) NOT NULL,
    image_url VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_offer_seller UNIQUE (auction_id, seller_id),
    CONSTRAINT uq_offer_request UNIQUE (auction_id, seller_id, request_key)
);
CREATE INDEX idx_offers_price ON offers(auction_id, amount, id);
ALTER TABLE auctions ADD CONSTRAINT fk_winning_offer FOREIGN KEY (winning_offer_id) REFERENCES offers(id);

CREATE TABLE trade_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id BIGINT NOT NULL UNIQUE REFERENCES auctions(id),
    product_id BIGINT NOT NULL UNIQUE REFERENCES products(id),
    seller_id BIGINT NOT NULL REFERENCES members(id),
    buyer_id BIGINT NOT NULL REFERENCES members(id),
    product_title VARCHAR(120) NOT NULL,
    amount BIGINT NOT NULL CHECK (amount BETWEEN 1 AND 1000000000000),
    status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING_PAYMENT')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (seller_id <> buyer_id)
);
CREATE INDEX idx_orders_buyer ON trade_orders(buyer_id, id DESC);
CREATE INDEX idx_orders_seller ON trade_orders(seller_id, id DESC);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES members(id),
    auction_id BIGINT NOT NULL REFERENCES auctions(id),
    type VARCHAR(30) NOT NULL CHECK (type IN ('OUTBID','AUCTION_WON','AUCTION_SOLD')),
    message VARCHAR(300) NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_notifications_recipient ON notifications(recipient_id, id DESC);
